fix-bug unpredictable state of tableAction.reorder's function
rowyio/rowy pull request #611
Opened 2021-12-28 11:32 UTC by gibsonliketheguitar

#559 
- Use .reduce() to carry out data swap, and 
- transform columns into a correct data structure for dispatch. 

I do request some clarification on the array mover.
- When is there an undefined element?

I really my chances are missing an edge case, assistance would be awesome.

2022-01-07 07:04 UTC, notsidney requested changes
For reorder, we want to move a column to a new position and push all columns right to make space, not swap the two columns’ positions.

2022-01-07 07:20 UTC, gibsonliketheguitar commented
Will do

2022-01-28 04:18 UTC, gibsonliketheguitar commented
![ready-im-ready](https://user-images.githubusercontent.com/66423127/151486580-dce2e3f9-a8ee-4270-9c3e-a63456e997c1.gif)

2022-01-31 05:54 UTC, shamsmosowi approved these changes

2022-01-31 05:55 UTC, merged